//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class aile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aile()
        {
            this.ailefert = new HashSet<ailefert>();
        }
    
        public int AileId { get; set; }
        public int TC { get; set; }
        public string AileAd { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public System.DateTime Guncelleme { get; set; }
        public Nullable<int> KurumId { get; set; }
    
        public virtual bagisyapan_kurum bagisyapan_kurum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ailefert> ailefert { get; set; }
    }
}
