//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ailefert
    {
        public int key_Id { get; set; }
        public int key_AileId { get; set; }
        public int TC { get; set; }
        public string AdSoyad { get; set; }
        public System.DateTime Kayıt { get; set; }
        public System.DateTime Guncelleme { get; set; }
    
        public virtual aile aile { get; set; }
    }
}
