//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aileEntities : DbContext
    {
        public aileEntities()
            : base("name=aileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aile> aile { get; set; }
        public virtual DbSet<ailefert> ailefert { get; set; }
        public virtual DbSet<bagisturu> bagisturu { get; set; }
        public virtual DbSet<bagisyapan_kurum> bagisyapan_kurum { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
    }
}
